<?php

if (!function_exists('skills')) {
    /**
     * Get lists skills
     * @return array
     */
    function skills(): array
    {
        return [
            "Sketching",
            "Watercolor painting",
            "Portrait drawing",
            "Figure sculpting",
            "Street photography",
            "Digital illustration",
            "Hip-hop dance",
            "Ballet dancing",
            "Sprinting",
            "Long-distance running",
            "High jump",
            "Diving",
            "Judo",
            "Karate",
            "Basketball dribbling",
            "Tennis serve",
            "Golf putting",
            "Logical reasoning",
            "Decision-making",
            "Data analysis",
            "Probability and statistics",
            "Algorithm design",
            "Fiction writing",
            "Scientific research methodology",
            "Presentation skills",
            "Conflict resolution",
            "Woodworking",
            "Plumbing repairs",
            "Electrical wiring",
            "TIG welding",
            "Automotive diagnostics",
            "Programming",
            "Web design",
            "Cybersecurity",
            "Industrial robotics",
            "French cuisine",
            "Baking pastries",
            "Knife skills",
            "Sauce making",
            "Wine pairing",
            "Cocktail mixing",
            "Cake decorating",
            "Food plating",
            "Pronunciation",
            "Grammar",
            "Translation",
            "Interpretation",
            "Writing and editing",
            "Poetry composition",
            "Language teaching",
            "Transcription",
            "Surgery techniques",
            "Medication administration",
            "Patient assessment",
            "Acupuncture therapy",
            "Massage techniques",
            "Herbal medicine knowledge",
            "Diagnostic skills",
            "Rehabilitation exercises",
            "Shelter building",
            "Fire making",
            "Navigation using a compass",
            "Knot tying",
            "Fishing",
            "Wild plant identification",
            "First aid skills",
            "Water purification techniques",
            "Aircraft navigation",
            "Engine troubleshooting",
            "Circuit board soldering",
            "3D modeling and printing",
            "CAD design",
            "Industrial automation",
            "Troubleshooting electronic devices",
            "Product prototyping",
            "Other"
        ];
    }
}