name: Automated Test in Github Actions

on:
  push:
    branches: ["main"]

jobs:
  tests:
    name: Run automated tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Copy testing environments
        run: |
          cp .env.ci .env
          cp .env.ci .env.testing

      - name: Install composer
        run: |
          composer install --no-interaction

      - name: Run test coverage
        run: |
          php artisan test
        env:
          DB_DATABASE: unilink

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: unilink
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=3